<?php

namespace SolucionesCucuta\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivoRepository extends EntityRepository
{
    public function getArchivosTipo($tipo, $results = true){
        $qb = $this->createQueryBuilder('a');
        if(is_numeric($tipo)){
            $qb->andWhere($qb->expr()->eq('a.tipo',$tipo));
        }elseif(is_string($tipo)){
            $qb ->join('a.tipo', 'at')
                ->andWhere($qb->expr()->eq('at.slug',$qb->expr()->literal($tipo)));
        }
        if($results === null){
            return $qb;
        }
        if(!$results){
            return $qb->getQuery();
        }
        return $qb->getQuery()->getResult();
    }

}
