<?php

namespace SolucionesCucuta\AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BasicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BasicRepository extends EntityRepository
{
    public function getAll(){
        return $this
            ->createQueryBuilder('a')
            ->orderBy('a.nombre','ASC');
    }
}
